### ISSUE TITLE
feature request: dircolors support

### ISSUE THREAD

**Issue by shabahengam** [joachimschmidt557/nimmm#1]
please add dircolors support.thanks

**Comment by joachimschmidt557** [comment]
Yes, this is definitely something worth implementing, but I think the functionality for colorizing directories and files should belong into a separate nimble package which doesn't exist yet as far as I'm aware and if no one is interested in implementing such a package, then I'll be willing to do so.

**Comment by joachimschmidt557** [comment]
I created a `lscolors` nimble package and integrated it into `nimmm`. The latest release now has lscolors support.

**Comment by shabahengam** [comment]
thanks.but after building nimmm nothing happens.i mean, i execute nimmm but it close immediately without any error.
EDIT: i made a new issue for this problem.
