### ISSUE TITLE
bug report: nimmm close immediately without any error message

### ISSUE THREAD

**Issue by shabahengam** [joachimschmidt557/nimmm#2]
i built nimmm(commit dee12cd) but it close immediately without any error message.
i get back commit by commit to 6467827 and built it again and now nimmm works.
problem is with commit 1729a35 and other commits after that.
please let me know if you need any further information.

**Comment by joachimschmidt557** [comment]
Do you have the `LS_COLORS` environment variable set? I'm guessing this might be the reason.

**Comment by shabahengam** [comment]
i have a customized dircolors file in "~/.dircolors" directory, if i delete that file everything is ok and nimmm use default colors.this is my customized [dircolors file](https://gist.github.com/shabahengam/9ce44d14d3fd30c9d5f8dc129d10620b)
ls can parse it correctly.[check this picture](https://0x0.st/zVQR.png)
this is the [original dircolors](https://gist.github.com/shabahengam/d3ea3d9cedd1be8c6b4125a22fa4368f) file that nimmm can parse correctly.

**Comment by joachimschmidt557** [comment]
Yup, I identified the problem:

https://gist.github.com/shabahengam/9ce44d14d3fd30c9d5f8dc129d10620b#file-dircolors-customized-L9

Seems like `target` is not handled yet. I will implement this in the `lscolors` package.

**Comment by joachimschmidt557** [comment]
I've now implemented `target` and 256-color display functionality. Can you test it on your machine? You'll need to enable 256-color mode by exporting `NIMMM_256="y"` or something.

**Comment by shabahengam** [comment]
yes,it works.thank you so much.
![image](https://user-images.githubusercontent.com/53096747/63192905-6cc9f600-c081-11e9-9686-5c92847a9d6a.png)
EDIT:
but as you said `NIMMM_256="y"` must be set or it doesn't show right colors.
![image](https://user-images.githubusercontent.com/53096747/63214643-051eb400-c130-11e9-951d-d2cf8f9d71e9.png)

**Comment by shabahengam** [comment]
i think the problem solved and we can close this issue.
