### ISSUE TITLE
feature request: accept path as an argument

### ISSUE THREAD

**Issue by shabahengam** [joachimschmidt557/nimmm#3]
for example if i type: `nimmm ~/Downloads` it should opens Downloads directory.

**Comment by joachimschmidt557** [comment]
I'll implement this but I think more command-line options shouldn't be necessary and would be going against the goal of simplicity. I'll also work on remapping keys in the coming days.

**Comment by joachimschmidt557** [comment]
I've added this feature in the latest commit.
