### ISSUE TITLE
Couldn't build application

### ISSUE THREAD

**Issue by kukushkawi** [joachimschmidt557/nimmm#5]
Hello. First of all, i really like the idea and your implementation and would like to contribute even though i'm still very much a beginner in Nim, but i couldn't get to compile nimmm on my machine. I tried compiling with "nimble build" and "nimble install", doublechecked if i have all of the dependencies, but still got this error:
nimmm.nim(114, 18) Error: undeclared identifier: 'Thread'
candidates (edit distance, scope distance); see '--spellSuggest'

**Comment by joachimschmidt557** [comment]
Hi, you need to use the `--threads:on` command-line flag when compiling nimmm. The full compile command would look like this:

```shell
nimble build --threads:on
```

I'll add this to the README too.

**Comment by kukushkawi** [comment]
Oh, i see now. Maybe I'll submit readme in pull request in a few minutes
